// Date: 11.06.2013 12:12:53
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package net.minecraft.src;

public class ModelBigPedestal extends ModelBase {
    //fields

    ModelRenderer Pedestal1;
    ModelRenderer Pedestal2;
    ModelRenderer Pedestal3;
    ModelRenderer Pedestal4;
    ModelRenderer Pedestal5;
    ModelRenderer Sign;

    public ModelBigPedestal() {
        textureWidth = 64;
        textureHeight = 32;

        Pedestal1 = new ModelRenderer(this, 0, 32);
        Pedestal1.addBox(0F, 0F, 0F, 16, 1, 16);
        Pedestal1.setRotationPoint(-8F, 23F, -8F);
        Pedestal1.setTextureSize(64, 32);
        Pedestal1.mirror = true;
        setRotation(Pedestal1, 0F, 0F, 0F);
        Pedestal2 = new ModelRenderer(this, 0, 32);
        Pedestal2.addBox(0F, 0F, 0F, 16, 1, 16);
        Pedestal2.setRotationPoint(-8F, 8F, -8F);
        Pedestal2.setTextureSize(64, 32);
        Pedestal2.mirror = true;
        setRotation(Pedestal2, 0F, 0F, 0F);
        Pedestal3 = new ModelRenderer(this, 0, 32);
        Pedestal3.addBox(0F, 0F, 0F, 14, 1, 14);
        Pedestal3.setRotationPoint(-7F, 22F, -7F);
        Pedestal3.setTextureSize(64, 32);
        Pedestal3.mirror = true;
        setRotation(Pedestal3, 0F, 0F, 0F);
        Pedestal4 = new ModelRenderer(this, 0, 32);
        Pedestal4.addBox(0F, 0F, 0F, 14, 1, 14);
        Pedestal4.setRotationPoint(-7F, 9F, -7F);
        Pedestal4.setTextureSize(64, 32);
        Pedestal4.mirror = true;
        setRotation(Pedestal4, 0F, 0F, 0F);
        Pedestal5 = new ModelRenderer(this, 0, 32);
        Pedestal5.addBox(0F, 0F, 0F, 12, 12, 12);
        Pedestal5.setRotationPoint(-6F, 10F, -6F);
        Pedestal5.setTextureSize(64, 32);
        Pedestal5.mirror = true;
        setRotation(Pedestal5, 0F, 0F, 0F);
        Sign = new ModelRenderer(this, 0, 56);
        Sign.addBox(0F, 0F, 0F, 10, 5, 1);
        Sign.setRotationPoint(-5F, 13F, -6.5F);
        Sign.setTextureSize(64, 32);
        Sign.mirror = true;
        setRotation(Sign, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5);
        Pedestal1.render(f5);
        Pedestal2.render(f5);
        Pedestal3.render(f5);
        Pedestal4.render(f5);
        Pedestal5.render(f5);
        Sign.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5);
    }
}
