// Date: 15.06.2013 21:58:01
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelVillsgerMemorial extends ModelBase
{
  //fields
    ModelRenderer Pedestal;
    ModelRenderer Pedestal2;
  
  public ModelVillsgerMemorial()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Pedestal = new ModelRenderer(this, 0, 0);
      Pedestal.addBox(0F, 0F, 0F, 16, 4, 16);
      Pedestal.setRotationPoint(-8F, 20F, -8F);
      Pedestal.setTextureSize(64, 32);
      Pedestal.mirror = true;
      setRotation(Pedestal, 0F, 0F, 0F);
      Pedestal2 = new ModelRenderer(this, 2, 2);
      Pedestal2.addBox(0F, 0F, 0F, 14, 4, 14);
      Pedestal2.setRotationPoint(-7F, 16F, -7F);
      Pedestal2.setTextureSize(64, 32);
      Pedestal2.mirror = true;
      setRotation(Pedestal2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Pedestal.render(f5);
    Pedestal2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
