// Date: 12.03.2014 0:06:48
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelModel extends ModelBase
{
  //fields
    ModelRenderer pedestal;
    ModelRenderer pedestal2;
  
  public ModelModel()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      pedestal = new ModelRenderer(this, 0, 68);
      pedestal.addBox(0F, 0F, 0F, 12, 1, 9);
      pedestal.setRotationPoint(-6F, 23F, -2F);
      pedestal.setTextureSize(128, 128);
      pedestal.mirror = true;
      setRotation(pedestal, 0F, 0F, 0F);
      pedestal2 = new ModelRenderer(this, 33, 68);
      pedestal2.addBox(0F, 0F, 0F, 8, 2, 5);
      pedestal2.setRotationPoint(-4F, 21F, 1F);
      pedestal2.setTextureSize(128, 128);
      pedestal2.mirror = true;
      setRotation(pedestal2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    pedestal.render(f5);
    pedestal2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
